version: '3'

services:
    dgital_nginx:
        container_name: dgital_nginx
        image: nginx:latest
        volumes:
            - ./:/var/www:delegated
            - ./_docker/nginx/conf.d/dgital.group.conf:/etc/nginx/conf.d/dgital.group.conf
            - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./_docker/nginx/ssl:/etc/nginx/ssl
        ports:
            - 443:443
        depends_on:
            -   dgital_app

    dgital_app:
        container_name: dgital_app
        build:
            context: .
            dockerfile: _docker/app/Dockerfile 
        volumes:
            - ./:/var/www
        depends_on:
            -   dgital_db
        env_file:
            -   .env

    dgital_db:
        container_name: dgital_db
        build: _docker/postgres 
        command:
            - "postgres"
            - "-c"
            - "max_connections=100"
            - "-c"
            - "shared_buffers=1GB"
            - "-c"
            - "effective_cache_size=4GB"
            - "-c"
            - "work_mem=16MB"
            - "-c"
            - "maintenance_work_mem=512MB"
            - "-c"
            - "random_page_cost=1.1"
            - "-c"
            - "temp_file_limit=10GB"
            - "-c"
            - "log_min_duration_statement=200ms"
            - "-c"
            - "idle_in_transaction_session_timeout=10s"
            - "-c"
            - "lock_timeout=60s"
            - "-c"
            - "statement_timeout=180s"
            - "-c"
            - "shared_preload_libraries=pg_stat_statements"
            - "-c"
            - "pg_stat_statements.max=10000"
            - "-c"
            - "pg_stat_statements.track=all"
            - "-c"
            - "log_statement=all"
            - "-c"
            - "log_rotation_age=120d"
            - "-c"
            - "log_directory=pg_log"
            - "-c"
            - "log_filename=postgresql-%Y-%m-%d_%H%M%S.log"
            - "-c"
            - "log_connections=on"
            - "-c"
            - "password_encryption=scram-sha-256" 
        ports:
            - $DB_OUTER_PORT:$DB_PORT
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            POSTGRES_DB: $DB_DATABASE
            PGDATA: "/var/lib/postgresql/data/pgdata"
            TZ: $DB_TIMEZONE
        volumes:
            - ./_docker/ldap/ldap.conf:/etc/ldap/ldap.conf
            - ./_docker/postgres/data:/var/lib/postgresql/data
            - ./_docker/postgres/common/postgresql-common.txt:/etc/logrotate.d/postgresql-common.txt 
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U postgres -d dgital"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G

    
    dgital_pgadmin:
        container_name: dgital_pgadmin
        image: dpage/pgadmin4 
        environment:
            PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
            PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_ENABLE_TLS: "True"
            PGADMIN_LISTEN_PORT: 9433
        volumes:
            - ./_docker/nginx/ssl/dgital.group.crt:/certs/server.cert
            - ./_docker/nginx/ssl/dgital.group.key:/certs/server.key
        ports:
            - 9433:9433
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 1G
        depends_on:
        - dgital_db

networks:
  default:
    external:
      name: projects_default